### ISSUE TITLE
Problem with geocoding

### ISSUE THREAD

**Issue by bocianl** [joachimruhs/mymap#2]
Hello,

First, thanks for a great extension.

I got problem with geocoding some polish cities for example.

TYPO3 10.4.12
Mymap 0.8.5

![image](https://user-images.githubusercontent.com/3082489/112192186-0a46bd80-8c07-11eb-9d45-a69b58db50d3.png)

**Comment by joachimruhs** [comment]
Hi,
just tested and should work...

Did the autocompleter work?

![image](https://user-images.githubusercontent.com/51224372/113206889-4960b880-9270-11eb-9ca2-f532249190df.png)

**Comment by joachimruhs** [comment]
Hi,
you can test it by yourself: https://www.web-services-ruhs.de/mymap

...

**Comment by bocianl** [comment]
Hello,

Thanks for checking and reply.

This is the result of the test:

![image](https://user-images.githubusercontent.com/3082489/113284775-6afe8600-92ea-11eb-9d49-6b7756d2b487.png)

Maybe it error is related to my location?

**Comment by bocianl** [comment]
When autocomplete is disabled this search works. This is related to autocomplete.

**Comment by joachimruhs** [comment]
Hi,

does other location in Poland works?

**Comment by bocianl** [comment]
Yes, only some cities have problems.

**Comment by joachimruhs** [comment]
have you 
Places API activ in Google 
console.cloud.google.com/apis/library/places-backend.googleapis.com?

**Comment by bocianl** [comment]
Yes, Places API and Embed Places API are enabled.

**Comment by joachimruhs** [comment]
try the search here
https://www.web-services-ruhs.de/mymap/searchform
ignore the country field and in the city field insert: Przemyśl, Polen and set radius to 5000 km!

**Comment by bocianl** [comment]
![image](https://user-images.githubusercontent.com/3082489/113292074-44454d00-92f4-11eb-9c2b-de2ef3f948c7.png)

**Comment by joachimruhs** [comment]
Hi, you have to set the Radius to 5000km!

**Comment by bocianl** [comment]
OK, this form working.

**Comment by joachimruhs** [comment]
How have you filled the country field of your locations? 2 letters?
Can I get the URL?

**Comment by bocianl** [comment]
No, just "Stadt" field with Przemyśl, Polen.

https://www.web-services-ruhs.de/mymap/result?tx_mymap_search%5Baction%5D=search&tx_mymap_search%5Bcontroller%5D=Location&cHash=60bb2c2f735d765088dc30121f2acff8

**Comment by joachimruhs** [comment]
Hi,

for the search it is a good to fill the "Stadt" with Przemyśl and the Country/Land with Polen...

**Comment by bocianl** [comment]
Ok this form working. What next? :)

![image](https://user-images.githubusercontent.com/3082489/113389926-1f52e780-9391-11eb-934b-920883dd4281.png)

![image](https://user-images.githubusercontent.com/3082489/113389940-24179b80-9391-11eb-92ba-99ed7d9e3b82.png)

**Comment by joachimruhs** [comment]
Hi,
in template AjaxSearch.html change
	<input id="tx_mymap_country" type="text" value="**DE" class="hidden"** to
	<input id="tx_mymap_country" type="text" value="PL"  
and test again...

or set the country value =""

**Comment by bocianl** [comment]
Hi, 
Unfortunately, changing to "PL" and "" did not help.

**Comment by joachimruhs** [comment]
Hi,
did you use the original templates?
When I test it, it works for me for Przemyśl

Did you load jquery on top of the page?

What is the URL?

**Comment by joachimruhs** [comment]
You have to find the issue why the autocompleter
did not work. May be  load jquery on top of the page.

**Comment by bocianl** [comment]
Url: https://www.ptp.dqcloud2.pl/dystrybutorzy
Yes, original templates, jquery at the top.

![image](https://user-images.githubusercontent.com/3082489/113727286-4729ae80-96f5-11eb-9e74-9eb0f9a7de06.png)

**Comment by joachimruhs** [comment]
ok, browser firefox:
autocompleter works,
ajaxsearch works

![image](https://user-images.githubusercontent.com/51224372/113731257-ec925180-96f8-11eb-9fbd-1866a2a5c3a2.png)

**Comment by bocianl** [comment]
Firefox, autocomplete: https://bck2233.tinytake.com/tt/NTI2MzA2MV8xNjQ2NjcwNg

**Comment by joachimruhs** [comment]
May be red question mark is because your ar in a subdomain.
You have to check the the AjaxLocationList template
and remove the slash /
	                <li><img src="/{image.originalResource.originalFile.publicUrl}" width="70" alt=""/>

**Comment by joachimruhs** [comment]
See here ... your website
you have to check for javascript errors or you have to debug the sorce why an error Geocoding-Error Zero results happens.

![image](https://user-images.githubusercontent.com/51224372/113733783-13518780-96fb-11eb-842b-b7268d82dbee.png)

**Comment by bocianl** [comment]
This is related to browser language. When it is set to German then works:

![image](https://user-images.githubusercontent.com/3082489/113733949-33814680-96fb-11eb-819a-90f94008768a.png)

**Comment by bocianl** [comment]
Polish browser language:

![image](https://user-images.githubusercontent.com/3082489/113734411-9ecb1880-96fb-11eb-8443-b81f4f07800d.png)

German browser language:

![image](https://user-images.githubusercontent.com/3082489/113734588-c02c0480-96fb-11eb-9e63-d2bc58ed9f46.png)

**Comment by joachimruhs** [comment]
you have to set the Country to PL in AjaxSearch.html the it works with Browser Language Polish.
Test here: https://www.web-services-ruhs.de/mymap

        <input id="tx_mymap_country" type="text" value="PL" placeholder="Land" class="hidden1"/>

**Comment by bocianl** [comment]
Joachim, Big Thank you for your help.

This error with geocode still exist on our test page:
https://cutt.ly/2cBkggZ

There is no other JS code and as You suggested country in the template file was changed to "PL"

**Comment by joachimruhs** [comment]
If I test your testpage all is ok... 
tested with firefox, edge and chrome...

In the data sent to the server there is still a

tx_mymap_ajax[country] | "DE" 
in. 
THAT  should be in your case PL.

For testing change javascript from

function geocodeByClient() {
		var country = $('#tx_mymap_country').val();

to

function geocodeByClient() {
		var country = "PL";


Is the error gone now...

**Comment by joachimruhs** [comment]
Hi,
I think I got it:

In javascript 
$(document).ready(function () {

	// show all locations when page is loaded
	$('#tx_mymap_city').val('Freiburg');
	$('#tx_mymap_country').val('DE');

the value for country is set to 'DE'. Please change that to 'PL' and
the city to a city of Poland...

What does the error do now?

**Comment by bocianl** [comment]
That was it :) Thank you!
Best regards.
